apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: production
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/NT505-P21-KLTN-ThienLM-PhuongQTH/kubernetes-hub.git
        path: .
        targetRevision: main
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
